Use -Werror on with `devel` flag enabled.
Because hackage is not accepting packages with -Werror enabled by
default due to ..

  yac@linux-1e2q % cabal upload dist/os-release-0.2.2.tar.gz
  Uploading dist/os-release-0.2.2.tar.gz...
  Error: dist/os-release-0.2.2.tar.gz: 400 Bad Request
  Error: Invalid package

  'ghc-options: -Wall -Werror' makes the package very easy to break with future
  GHC versions because new GHC versions often add new warnings. Use just
  'ghc-options: -Wall' instead. If you want to use this, make it conditional
  based on a flag (with 'manual: True' and 'default: False') and enable that
  flag during development.

Fixes #2